apiVersion: v1
kind: Pod
metadata:
  name: soamonitor
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: SOASchedulerURL
      value: "http://soaweblogic.production.tervis.prv:7201/SOAScheduler/soaschedulerservlet?action=read"
    - name: NotificationEmailAddress
      value: "cmagnuson@tervis.com"
