#apiVersion: v1
#kind: Pod
#metadata:
#  name: powershellapplications
#spec:
#  containers:
#  - name: tervissoamonitoringapplication
#    image: tervis/tervissoamonitoringapplication:0.0.1
#    env:
#    - name: SOASchedulerURL
#      value: "http://soaweblogic.production.tervis.prv:7201/SOAScheduler/soaschedulerservlet?action=read"
#    - name: EmailTo
#      value: "cmagnuson@tervis.com"
#    - name: EmailFrom
#      value: "cmagnuson@tervis.com"

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tervissoamonitoringapplication
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tervissoamonitoringapplication
            image: tervis/tervissoamonitoringapplication:0.0.1
            env:
            - name: SOASchedulerURL
              value: "http://soaweblogic.production.tervis.prv:7201/SOAScheduler/soaschedulerservlet?action=read"
            - name: EmailTo
              value: "cmagnuson@tervis.com"
            - name: EmailFrom
              value: "cmagnuson@tervis.com"
          restartPolicy: OnFailure
